---
- name: demo app code
  copy:
    src: files/
    dest: "{{ wsid_demo_client_app_installation_dir }}/"
  notify: reload uwsgi
- apt:
    name: 
      - apache2-utils
      - python3
      - python3-pip
      - uwsgi-emperor
      - uwsgi-plugin-python3
      - python3-flask
      - python3-requests
- pip:
    name: 
      - paramiko>=2.2
    executable: pip3
- systemd:
    name: "uwsgi-emperor"
    enabled: yes
    state: started
- name: uwsgi vassal config
  template:
    dest: /etc/uwsgi-emperor/vassals/demo_uwsgi.ini
    src: uwsgi.ini
- include_tasks: "{{ role_path }}/tasks/rotation_hook.yml"
  loop:
    - dir: "{{ wsid_hooks_key_dir }}/{{ wsid_demo_identity }}"
      file: id_ed25519
    - dir: "{{ wsid_hooks_passwd_dir }}/{{ wsid_demo_identity }}"
      file: passwd
  loop_control:
    loop_var: hook
    label: "hook:{{ hook.file }}"
