---
- user:
    name: "{{ wsid_demo_ssh_user }}"
- lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitUserEnvironment
    line: PermitUserEnvironment yes
    validate: /usr/sbin/sshd -t -f %s
  notify: reload sshd
- blockinfile:
    dest: /etc/ssh/sshd_config
    block: "{{ lookup('template', 'sshd_config_addon') }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: reload sshd
#- lineinfile:
#    line: "Include sshd_demo_dynamic_auth"
#    dest: /etc/ssh/sshd_config
#  notify: restart sshd
