---
- file:
    dest: /opt/nginx-letsencrypted/data/configs
    state: directory
- template:
    dest: /opt/nginx-letsencrypted/data/configs/default.conf
    src: nginx.conf
- apt:
    name: 
      - python3
      - uwsgi-emperor
      - python3-flask
      - python3-requests
