---
- name: restart sshd
  service:
    name: sshd
    state: restarted
- name: restart demo app
  include_tasks: "{{ role_path }}/handlers/demo_docker_{{ docker_service_or_compose }}.yml"
- name: restart auth app
  include_tasks: "{{ role_path }}/handlers/auth_docker_{{ docker_service_or_compose }}.yml"
