---
- name: restart sshd
  service:
    name: sshd
    state: restarted
- include: docker_service.yml
  when: ansible_version.full is version('2.8','<') 
- include: docker_compose.yml
  when: ansible_version.full is version('2.8','>=') 
