---
- stat:
    path: "{{ wsid_demo_client_app_installation_dir }}"
  register: codebase_preinstalled
- name: demo app code
  copy:
    src: files/
    dest: "{{ wsid_demo_client_app_installation_dir }}/"
  register: wsid_demo_app_codebase
- apt:
    name: 
      - apache2-utils
      - python3
      - python3-pip
      - uwsgi-emperor
      - uwsgi-plugin-python3
      - python3-flask
      - python3-requests
- pip:
    name: 
      - paramiko>=2.2
    executable: pip3
- systemd:
    name: "uwsgi-emperor"
    enabled: yes
    state: started
- template:
    dest: /etc/uwsgi-emperor/vassals/demo_uwsgi.ini
    src: uwsgi.ini
  register: wsid_demo_vassal_config
- name: emperor service
  service:
    name: "uwsgi-emperor"
    enabled: yes
    state: "{{ 'reloaded' if codebase_preinstalled.stat.exists else 'started' }}"
  when: wsid_demo_vassal_config.changed or wsid_demo_app_codebase.changed
- name: wsid rotation hook directory
  file:
    dest: "{{ wsid_hooks_key_dir }}/{{wsid_demo_identity}}"
    state: directory
- name: wsid rotation hook 
  template:
    src: hook.sh
    dest: "{{ wsid_hooks_key_dir }}/{{wsid_demo_identity}}/00_uwsgi_reload.sh"
    mode: 0744
