---
- stat:
    path: "{{ wsid_demo_client_app_installation_dir }}"
  register: codebase_preinstalled
- name: demo app code
  copy:
    src: files/
    dest: "{{ wsid_demo_client_app_installation_dir }}/"
  register: wsid_demo_app_codebase
- apt:
    name: 
      - apache2-utils
      - python3
      - uwsgi-emperor
      - uwsgi-plugin-python3
      - python3-flask
      - python3-requests
- systemd:
    name: "uwsgi-emperor"
    enabled: yes
    state: started
- template:
    dest: /etc/uwsgi-emperor/vassals/demo_uwsgi.ini
    src: uwsgi.ini
  register: wsid_demo_vassal_config
- name: emperor service
  service:
    name: "uwsgi-emperor"
    enabled: yes
    state: "{{ 'reloaded' if codebase_preinstalled.stat.exists else 'started' }}"
  when: wsid_demo_vassal_config.changed or wsid_demo_app_codebase.changed
- name: wsid rotation hooks
  copy:
    content: |
        #! /bin/bash
        /usr/sbin/service uwsgi-emperor reload 2>&1 | logger -e -s -t wsid
    dest: "{{ item }}"
    mode: 0744
  loop:
    - "{{ wsid_hooks_passwd_dir }}/{{wsid_demo_identity}}/00_uwsgi_reload.sh"
    - "{{ wsid_hooks_key_dir }}/{{wsid_demo_identity}}/00_uwsgi_reload.sh"
